package com.hao.novel.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hao.novel.spider.data.NovelIntroduction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOVEL_INTRODUCTION".
*/
public class NovelIntroductionDao extends AbstractDao<NovelIntroduction, Long> {

    public static final String TABLENAME = "NOVEL_INTRODUCTION";

    /**
     * Properties of entity NovelIntroduction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NovelNameAndAutho = new Property(1, String.class, "novelNameAndAutho", false, "NOVEL_NAME_AND_AUTHO");
        public final static Property NovelName = new Property(2, String.class, "novelName", false, "NOVEL_NAME");
        public final static Property NovelAutho = new Property(3, String.class, "novelAutho", false, "NOVEL_AUTHO");
        public final static Property NovelCover = new Property(4, String.class, "novelCover", false, "NOVEL_COVER");
        public final static Property NovelIntroduce = new Property(5, String.class, "novelIntroduce", false, "NOVEL_INTRODUCE");
        public final static Property NovelNewChapterTitle = new Property(6, String.class, "novelNewChapterTitle", false, "NOVEL_NEW_CHAPTER_TITLE");
        public final static Property NovelNewChapterUrl = new Property(7, String.class, "novelNewChapterUrl", false, "NOVEL_NEW_CHAPTER_URL");
        public final static Property NovelChapterListUrl = new Property(8, String.class, "novelChapterListUrl", false, "NOVEL_CHAPTER_LIST_URL");
    }


    public NovelIntroductionDao(DaoConfig config) {
        super(config);
    }
    
    public NovelIntroductionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOVEL_INTRODUCTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOVEL_NAME_AND_AUTHO\" TEXT UNIQUE ," + // 1: novelNameAndAutho
                "\"NOVEL_NAME\" TEXT," + // 2: novelName
                "\"NOVEL_AUTHO\" TEXT," + // 3: novelAutho
                "\"NOVEL_COVER\" TEXT," + // 4: novelCover
                "\"NOVEL_INTRODUCE\" TEXT," + // 5: novelIntroduce
                "\"NOVEL_NEW_CHAPTER_TITLE\" TEXT," + // 6: novelNewChapterTitle
                "\"NOVEL_NEW_CHAPTER_URL\" TEXT UNIQUE ," + // 7: novelNewChapterUrl
                "\"NOVEL_CHAPTER_LIST_URL\" TEXT UNIQUE );"); // 8: novelChapterListUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOVEL_INTRODUCTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NovelIntroduction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String novelNameAndAutho = entity.getNovelNameAndAutho();
        if (novelNameAndAutho != null) {
            stmt.bindString(2, novelNameAndAutho);
        }
 
        String novelName = entity.getNovelName();
        if (novelName != null) {
            stmt.bindString(3, novelName);
        }
 
        String novelAutho = entity.getNovelAutho();
        if (novelAutho != null) {
            stmt.bindString(4, novelAutho);
        }
 
        String novelCover = entity.getNovelCover();
        if (novelCover != null) {
            stmt.bindString(5, novelCover);
        }
 
        String novelIntroduce = entity.getNovelIntroduce();
        if (novelIntroduce != null) {
            stmt.bindString(6, novelIntroduce);
        }
 
        String novelNewChapterTitle = entity.getNovelNewChapterTitle();
        if (novelNewChapterTitle != null) {
            stmt.bindString(7, novelNewChapterTitle);
        }
 
        String novelNewChapterUrl = entity.getNovelNewChapterUrl();
        if (novelNewChapterUrl != null) {
            stmt.bindString(8, novelNewChapterUrl);
        }
 
        String novelChapterListUrl = entity.getNovelChapterListUrl();
        if (novelChapterListUrl != null) {
            stmt.bindString(9, novelChapterListUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NovelIntroduction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String novelNameAndAutho = entity.getNovelNameAndAutho();
        if (novelNameAndAutho != null) {
            stmt.bindString(2, novelNameAndAutho);
        }
 
        String novelName = entity.getNovelName();
        if (novelName != null) {
            stmt.bindString(3, novelName);
        }
 
        String novelAutho = entity.getNovelAutho();
        if (novelAutho != null) {
            stmt.bindString(4, novelAutho);
        }
 
        String novelCover = entity.getNovelCover();
        if (novelCover != null) {
            stmt.bindString(5, novelCover);
        }
 
        String novelIntroduce = entity.getNovelIntroduce();
        if (novelIntroduce != null) {
            stmt.bindString(6, novelIntroduce);
        }
 
        String novelNewChapterTitle = entity.getNovelNewChapterTitle();
        if (novelNewChapterTitle != null) {
            stmt.bindString(7, novelNewChapterTitle);
        }
 
        String novelNewChapterUrl = entity.getNovelNewChapterUrl();
        if (novelNewChapterUrl != null) {
            stmt.bindString(8, novelNewChapterUrl);
        }
 
        String novelChapterListUrl = entity.getNovelChapterListUrl();
        if (novelChapterListUrl != null) {
            stmt.bindString(9, novelChapterListUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NovelIntroduction readEntity(Cursor cursor, int offset) {
        NovelIntroduction entity = new NovelIntroduction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // novelNameAndAutho
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // novelName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // novelAutho
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // novelCover
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // novelIntroduce
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // novelNewChapterTitle
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // novelNewChapterUrl
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // novelChapterListUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NovelIntroduction entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNovelNameAndAutho(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNovelName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNovelAutho(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNovelCover(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNovelIntroduce(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNovelNewChapterTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setNovelNewChapterUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setNovelChapterListUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NovelIntroduction entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NovelIntroduction entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NovelIntroduction entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
